### ISSUE TITLE
Pester output?

### ISSUE THREAD

**Issue by davidwallis** [RamblingCookieMonster/PSHTMLTable#2]
Before I go digging and re-inventing the wheel - have you ever used this on the output of pester when used with -passthru?

Format-pester isn't quite what I need and seems a bit OTT 

David

**Comment by RamblingCookieMonster** [comment]
I haven't!  If you end up playing with it, feel free to post something up here or to link back to something, would be curious to see!

**Comment by davidwallis** [comment]
Will have a play Monday and let you know

**Comment by davidwallis** [comment]
Submitted a PR with a pester example in :)
